### ISSUE TITLE
Prendre en charge les tableaux

### ISSUE THREAD

**Issue by emchateau** [EcrituresNumeriques/spip2erudit#25]
Tableaux non pris en charge dans la sortie
- 1872ear
- 2212ear

**Comment by laurentdm** [comment]
J'ai tenté une mise en forme manuelle des tableaux dans le 1124 et 1152. Faudra voir comment ça sort, mais Oxygen me dit que c'est valide. Assez long à faire, par contre.

**Comment by emchateau** [comment]
Si c'est trop galère, on avait dit que l'on pourrait faire des images. Mais je ne suis pas fan.
