### ISSUE TITLE
Baliser les liens

### ISSUE THREAD

**Issue by emchateau** [EcrituresNumeriques/spip2erudit#28]
1215ear liens non balisé note 10

**Comment by laurentdm** [comment]
Par contre, je n'avais jamais fait la révision du 1215, ni d'aucun article au-dessus du 1188. Ces fichiers ne sont pas non plus dans le Spip2erudit/xml.
EDIT : Ah, d'accord. Le 1215 est l'identifiant d'Érudit et non de SP.

**Comment by emchateau** [comment]
érudit a modifié tous les identifiants (très pratique n’est-ce pas?)
