### ISSUE TITLE
Corriger les notes tronquées

### ISSUE THREAD

**Issue by emchateau** [EcrituresNumeriques/spip2erudit#8]
Les notes sont tronquées dans l’export XML de 997-article
Il y a manifestement un problème lorsque la note débute par un lien http://www.sens-public.org/article997.html note 1 et 3

**Comment by emchateau** [comment]
Le problème intervient également en deuxième.

**Comment by laurentdm** [comment]
Le problème intervient également de façon d'apparence aléatoire lorsque la note ne commence pas par un lien. Voir note 6 et 7 du 997. J'ai l'impression qu'il faudrait vérifier manuellement chaque note de chaque article une à une, ce qui risque d'être (très) long.

**Comment by laurentdm** [comment]
Les notes sont également tronquées lorsqu'il y a un saut de ligne dans la note. Voir le 1124 (http://www.sens-public.org/article1124.html), qui contient des notes avec des listes (note 14 et 30); le 1138 (note 75), 1152 (note 3), etc. qui contiennent une ou des notes avec saut de ligne.
